/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_b.view;

import uts_b.controller.PenjualanController;

/**
 *
 * @author Axioo
 */
public class FormPenjualan extends javax.swing.JFrame {

    /**
     * Creates new form FormPenjualan
     */
    public FormPenjualan() {
        initComponents();
        /*controller = new PenjualanController(this);
        controller.clearForm();
        controller.tampil();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKodepesanan = new javax.swing.JTextField();
        txtTgl = new javax.swing.JTextField();
        txtNamapemesan = new javax.swing.JTextField();
        txtTotalbayar = new javax.swing.JTextField();
        txtOngkoskirim = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PENJUALAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(252, 24, 88, 20);

        jLabel2.setText("Kode Pesanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(87, 81, 98, 20);

        jLabel3.setText("Tgl");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 110, 23, 20);

        jLabel4.setText("Nama Pemesan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(87, 148, 109, 20);

        jLabel5.setText("Total Bayar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 180, 80, 20);

        jLabel6.setText("Ongkos Kirim");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 220, 96, 20);

        jLabel7.setText("Diskon");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 260, 48, 20);

        txtKodepesanan.setText("jTextField1");
        getContentPane().add(txtKodepesanan);
        txtKodepesanan.setBounds(250, 80, 260, 26);

        txtTgl.setText("jTextField2");
        getContentPane().add(txtTgl);
        txtTgl.setBounds(250, 110, 260, 26);

        txtNamapemesan.setText("jTextField3");
        getContentPane().add(txtNamapemesan);
        txtNamapemesan.setBounds(250, 150, 260, 26);

        txtTotalbayar.setText("jTextField4");
        getContentPane().add(txtTotalbayar);
        txtTotalbayar.setBounds(250, 180, 260, 26);

        txtOngkoskirim.setText("jTextField5");
        getContentPane().add(txtOngkoskirim);
        txtOngkoskirim.setBounds(250, 220, 260, 26);

        txtDiskon.setText("jTextField6");
        getContentPane().add(txtDiskon);
        txtDiskon.setBounds(250, 260, 260, 26);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(90, 330, 73, 29);

        btnUpdate.setText("Update");
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(220, 330, 83, 29);

        btnDelete.setText("Delete");
        getContentPane().add(btnDelete);
        btnDelete.setBounds(350, 330, 77, 29);

        btnCancel.setText("Cancel");
        getContentPane().add(btnCancel);
        btnCancel.setBounds(500, 330, 79, 29);

        btnCari.setText("Cari");
        getContentPane().add(btnCari);
        btnCari.setBounds(560, 80, 61, 29);

        btnExit.setText("Exit");
        getContentPane().add(btnExit);
        btnExit.setBounds(630, 330, 59, 29);

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pesanan", "Tgl", "Nama Pemesan", "Total Bayar", "Ongkos Kirim", "Diskon", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblPenjualan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 390, 760, 402);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenjualan().setVisible(true);
            }
        });
    }

    public Object getTxtKodepesanan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtKodepesanan;
    private javax.swing.JTextField txtNamapemesan;
    private javax.swing.JTextField txtOngkoskirim;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txtTotalbayar;
    // End of variables declaration//GEN-END:variables

}
